### ISSUE TITLE
white screen issue

### ISSUE THREAD

**Issue by nirhenn** [homeworkc/lazycast#33]
I setup Lazycast on PI3 with 7" LCD and at start it works fine, i have my Win 10 desktop on the PI3 screen but after few min that i am working with it turns white with "untitled" in the caption and loos the desktop that i am streaming. 
From connection it looks fine all is working just loosing the desktop stream, any idea?

Another issue i have is that it is not utilizing the compleet screen size, i have a black frame around the desktop image. any way to optimize that?
Nir

**Comment by homeworkc** [comment]
It is due to the unexpected crash of player2. There is a engineering fix in [this](https://github.com/homeworkc/lazycast/issues/25) issue. Player1 seems to be more tolerant.

Are you using Android or Windows source? For Windows, you should adjust the screen resolution so that it match the resolution of the screen connected to Pi.
